### ISSUE TITLE
Move repo to JuliaIO Github org

### ISSUE THREAD

**Issue by scls19fr** [JuliaIO/LibSerialPort.jl#20]
Hello,

I wonder if moving this repository to [JuliaIO](https://github.com/JuliaIO) won't help to collectively maintain this package.
What is your opinion @andrewadare ?

Kind regards

PS : pinging also some public members of JuliaIO : @ararslan @tanmaykm @sjkelly

**Comment by andrewadare** [comment]
Back in 2016, my thinking was to [merge](https://github.com/JuliaIO/SerialPorts.jl/issues/14) the LibSerialPort.jl source into SerialPorts.jl since the latter was already registered and in use. Work on that [began](https://github.com/JuliaIO/SerialPorts.jl/pull/20) by @sjkelly, but I never put in any effort to follow through on it.  My idea was that, once done, there would be no need for LibSerialPort.jl and it would die off as a standalone package so that there would be one good choice for users. That's why LibSerialPort.jl has been unregistered this whole time.

But since then, talented community members have improved LibSerialPort.jl, giving it Windows support, improving docs, and keeping it up with Julia. It seems solid and performant on Julia 0.7/1.0 in my usage, and I'm now thinking that with just a bit more polish, there's a place for it in this world as a registered package.

I think that https://github.com/JuliaIO/SerialPorts.jl/issues/14 can still be addressed. But instead of literally moving this source there and figuring out conditional builds for python vs. libserialport backends, can we register LibSerialPort.jl and use the package system instead? The downside is that there would be two registered packages that do the same thing. On the other hand, this seems like a path that would be simpler to implement, more maintainable, and less disruptive.

**Comment by scls19fr** [comment]
My opinion is that https://github.com/JuliaIO/SerialPorts.jl should be renamed to "PySerialPorts" and be registered with this name instead of SerialPorts which is too generic.
LibSerialPort should also be registered
On the other side I think SerialPorts.jl should be unregistered, or at least deprecated, telling users to install LibSerialPort or PySerialPorts because the goal of having a generic package which works with either LibSerialPort or PySerialPorts is not yet done.
To implement a correct SerialPorts.jl we need to deal with optional dependencies and that's an other story (maybe using [Require.jl](https://github.com/mikeInnes/Requires.jl))

**Comment by tknopp** [comment]
@andrewadare: In any way registering LibSerialPorts is important. And this should be done as long as this package works on Julia 0.6. This will allow to drop 0.6 support in the future without affecting Julia 0.6 users which is important for backwards compatibility.

**Comment by scls19fr** [comment]
I've just create a PR to see if tests are still passing with Julia 0.6
https://github.com/andrewadare/LibSerialPort.jl/pull/28 (seeing in fact if there is more error with Julia 0.6 than Julia 0.7 and 1.0)
I personally don't use Julia 0.7 any more but I understand that it can be a problem.
Maybe we should have [tag a release](https://github.com/andrewadare/LibSerialPort.jl/issues/27) with Julia 0.6 support before.

**Comment by sjkelly** [comment]
I am willing to continue the integration of LibSerialPort and SerialPorts so there are two options for a given environment. Is it an acceptable approach to register this library, make a new PySerialPorts library, and keep SerialPorts as the generic interface for either backend?

**Comment by tknopp** [comment]
This would be the best approach if it is feasible to have the same interface. `SerialPorts` would then implement only the abstract interface (Have a look at Graphics.jl which does exactly that), whereas the user can then decide which package to actually use.

**Comment by andrewadare** [comment]
>  Is it an acceptable approach to register this library, make a new PySerialPorts library, and keep SerialPorts as the generic interface for either backend?

This makes sense to me. With a bit of documentation, I don't think it would be confusing for users at all. Seems there's a good precedent for this with Plots.jl, or as @tknopp mentioned, Graphics.jl.

**Comment by andrewadare** [comment]
As far as I can tell, everyone is in agreement. One concern I have is my lack of Windows experience. I would prefer if #22 were resolved and all tests pass on Windows before registering, otherwise we'll be flooded with issues. Is anyone able/willing to help out in that area?

**Comment by tknopp** [comment]
I would not fear any flooding of issues. Registering a package does not mean that all issues need to be resolved. Its quite the contrary. Lets say that the interface changes because PySerialPorts.jl and LibSerialPorts.jl need to be aligned. Then you defiantly need the versioning that you will get through the registration of the package. Without that all the users are always on master and every change you commit is seen by its users.

Unfortunately, I have just linux / mac here so cannot test on windows.

**Comment by sjkelly** [comment]
@andrewadare In addition to #22, can you give me a day or two to add docs? This way I can be sure that the API is common enough to have a seamless switch between LibSerialport on Unix and PySerial on Windows in SerialPorts.jl.

**Comment by andrewadare** [comment]
Thanks! And definitely, take the time you need. I can't attend to registering this package immediately anyway; I'll need some time myself to get to it.

**Comment by tknopp** [comment]
@andrewadare: Just in case you are not aware of it. Registering a package using attobot 
  https://github.com/attobot/attobot
is the easiest way nowadays. Its just a few clicks an the pull request to METADATA is done automatically.

**Comment by andrewadare** [comment]
The repo has been transferred to JuliaIO, and work is underway to get it registered. I think we can close this now.
