### ISSUE TITLE
avoid duplicating read functions from base/io.jl

### ISSUE THREAD

**Issue by mgkuhn** [JuliaIO/LibSerialPort.jl#58]
Is this package really the right place to duplicate various `IO` read utility functions from Base, just to add a timeout argument?

After all, the need to read from a byte stream with a timeout is not specific to serial ports in any way: you need the same functionality from lots of other character devices (TCP sockets, stdin from a terminal, GPIB interfaces, etc.).

Therefore, it would make sense to find ways to deal with this without duplicating code. The `LibSerialPort` high-level API should probably just implement the basic `read(s::SerialPort, ::Type{UInt8})`, `unsafe_read(s::SerialPort, p::Ptr{UInt8}, n::UInt)` and `peek(s::SerialPort)` methods expected by all `IO` subtypes, and inherit all the higher-level read utility functions from `IO`. (In essence, doing for reading what PR #56 does for writing.)

One example solution:

We could add a `read_timeout` parameter to the `SerialPort` struct. As long as `read_timeout < Inf`, then the `read(s::SerialPort, ::Type{UInt8})`, `unsafe_read(s::SerialPort, p::Ptr{UInt8}, n::UInt)` and `peek(s::SerialPort)` implementations should record the time `t1` they were called, pass `timeout` to the low-level API, record the time `t2-t1` spent there, and subtract it from `read_timeout`. If `read_timeout` reaches zero, they could throw a `TimeoutException` to abort any higher-level utility functions that called them. From a user's point of view, if you want to call any function with a read timeout, just call `set_read_timeout(sp, timeout)` first, and be prepared that the subsequent read method call comes back with a `TimeoutException`. To disable timeouts use `set_read_timeout(sp, Inf)`. The default for `read_timeout` should be `Inf`, whereas `read_timeout ≤ 0` might be used to cause invocation of the non-blocking read functions of the low-level API.

This way, users have full control over timeouts and blocking/non-blocking behaviour, _without_ changing the parameter signature of `IO` functions, or duplicating them.

(Are there other solutions, e.g. involving Julia's asynchronous event or multi-threading APIs?)

**Comment by andrewadare** [comment]
> Is this package really the right place to duplicate various IO read utility functions from Base, just to add a timeout argument?

Unfortunately, it's even worse than this, there's also some internal duplication. Additional `readuntil` methods were added in #45 via the new file utils.jl. I missed my chance to point this out before it was merged, and it hasn't been addressed since. Some of the read methods are already defined in high-level-api.jl, but they were not obvious because their names are not exported from the module. I think that utils.jl should be removed from the package first (and the README examples updated), then we can decide what to do with the `read*` methods in high-level-api.jl.

I have a branch underway to start working on the various `read` problems you have identified in several different issues, but I'm not sure that I'll make progress faster than you.

**Comment by mgkuhn** [comment]
Fixed in release `v0.5.0`.
